services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: inmogest-front
    ports:
      - "5173:80"  # ✅ Cambiado: puerto 80 del contenedor mapeado al 5173 del host
    environment:
      - VITE_API_URL=https://inmogestpro.com/api
    env_file:
      - .env
    restart: always
    networks:
      - inmogest-network

# Usar la red externa que ya existe del backend
networks:
  inmogest-network:
    external: true
    name: inmogest-network